apiVersion: v1
kind: Pod
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe convert
    kompose.version: 1.28.0 (c4137012e)
  creationTimestamp: null
  labels:
    io.kompose.network/spring-net: "true"
    io.kompose.service: pokemonimg-service
  name: pokemonimg-service
spec:
  containers:
    - image: teunbuis/pogokwetter:pokemonimg-service
      name: pokemonimg-service
      ports:
        - containerPort: 8081
      resources: {}
  restartPolicy: OnFailure
status: {}
